### ISSUE TITLE
Generate schema from sample document

### ISSUE THREAD

**Issue by gianpaj** [buzzm/ipsum#2]
First of all thanks alot for this Buzz!

We often need to replicate issues with customer and it would take a lot to generate a custom JS script to generate random documents for this.

Only only issue when first started using _ipsum_ was that it takes quite some time to pick what fields should be generated with what.

So it would be great if you could pass a file with a json object and get and proposed schema, at least to begin with so you wouldn't need to type manually the simple fields.

Maybe even say create the default schema except these fields. As most of the time it's just few that you would need to query and/or update.

**Comment by buzzm** [comment]
Ah!   There's already a thing out there that takes a candidate JSON document and reverses a schema out of it:
http://www.jsonschema.net

**Comment by gianpaj** [comment]
Cool stuff.
Maybe it would be good to add to the readme for anybody who won't find or look in github issues.
